compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  startings: [html, head, body]

exclude:
  - assets/entrypoints.json
  - assets/manifest.json
  - bin
  - Makefile
  - README.md
  - '*.config.js'
  - gifs.json
  - 'package*.json'
