name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
      MEILI_HOST: https://search.mlo.io
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: npm install
      - run: make index
        env:
          MEILI_PRIVATE_KEY: ${{ secrets.MEILI_PRIVATE_KEY }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::603767838523:role/gifs
      - run: make deploy
        env:
          MEILI_PUBLIC_KEY: ${{ secrets.MEILI_PUBLIC_KEY }}
